# Dockerfile for BullMQ & MTProto Worker
FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache python3 make g++ openssl libc6-compat

COPY package.json package-lock.json* ./
COPY prisma ./prisma/
ENV NODE_ENV=development
RUN npm ci --include=dev

COPY . .
RUN npx prisma generate

CMD ["npx", "tsx", "src/worker/index.ts"]
